Deltares/hydromt_wflow

- docs/changelog.rst
- hydromt_wflow/wflow.py
See #109 : solution is to use xr.to_datetimeindex instead of pd.to_datetime to convert times in forcing DataArrays
> Bug #109 forcing with DatetimeNoLeap

- docs/api.rst
- docs/changelog.rst
- docs/user_guide/sediment_model_setup.rst
- docs/user_guide/wflow_model_setup.rst
- hydromt_wflow/wflow.py
- tests/test_model_methods.py
Can be used to solve #128 
This method allows to add wflow variables from direct raster data (eg USLE parameter or altitude, ksatver etc.)
The function also allows to update the toml file in order to still get ready to run model with the new staticmaps.
> Added setup_staticmaps_from_raster 

- .github/workflows/publish.yml
> Better publishing

- examples/README.rst
- pyproject.toml
Fixes #206 
I think the installation was already updated but the examples not fully (installing jupyter and downloading the correct version of the examples).
I also do not think we need matplotlib-base in the [examples] install list as matplotlib is already installed and matplotlib-base is not installable with pip.
In hydromt core or the delft3dfm plugin, I recommend installing from pypi like so:
pip install "hydromt[slim]"
This avoids that people need to manually add libraries in [extra] and [examples] one by one or clone the github repository.
It does not work at the moment because of the matplolib-base library in [examples] (which I now removed) and the pcraster library in [extra]. 
I think an easy way to install and run the examples would be nice. For this, maybe we could move the …
> Update examples installation

- pyproject.toml
Fixes #233 
Pin the nbconvert package.
No
> Notebook progressbar fix

- docs/changelog.rst
- hydromt_wflow/wflow.py
- hydromt_wflow/workflows/basemaps.py
- tests/test_model_methods.py
Fixes #245 
Fixes #246 
For #245, seems there was only one case subcatch dtype was not np.int32. Rather than fixing the hydromt get_basin_geometry workflow I chose to force np.int32 dtype so that a different basins dtype in local hydrography would then also be supported.
For #246, just use the wflow_subcatch ID. I chose to just have this happen all the time rather than add an user option to still get random IDs.
> Several basin related fixes

- docs/api.rst
- docs/changelog.rst
- examples/build_model.ipynb
- hydromt_wflow/wflow.py
- hydromt_wflow/workflows/connect.py
Fixes #256 
We removed default merit_hydro value in setup_basemaps so the example of building a model without suppliying a config file does not work anymore.
The behavior is anyway not common and will be deprecated in hydromt v1 so I now removed that part of the example.
> update wflow build notebook

- docs/changelog.rst
- hydromt_wflow/workflows/landuse.py
Fixes #289
An error was raised because the columns 1 to 12 could not be found. This is caused by reading them as a string. This is solved by checking if there are digit columns and converting them to integers. This has been tested with a Wflow model for which a mapping table was created with `setup_lulcmaps`, and which is read by `setup_laimaps_from_lulc_mapping` in `lai_mapping_fn`.
> Bugfix when reading mapping table in lai lulc workflow

- docs/changelog.rst
- examples/linux64/wflow_piave_clip/wflow_sbm.toml
- examples/linux64/wflow_piave_subbasin/wflow_sbm.toml
- examples/linux64/wflow_piave_subbasin/wflow_sbm_results.toml
- examples/linux64/wflow_piave_subbasin/wflow_sbm_results2.toml
- examples/linux64/wflow_sediment_piave_subbasin/wflow_sediment.toml
- examples/wflow_piave_clip/wflow_sbm.toml
- examples/wflow_piave_subbasin/wflow_sbm.toml
- examples/wflow_piave_subbasin/wflow_sbm_results.toml
- examples/wflow_piave_subbasin/wflow_sbm_results2.toml
- examples/wflow_sediment_piave_subbasin/wflow_sediment.toml
- examples/wflow_update_forcing.yml
- hydromt_wflow/data/wflow/wflow_sbm.toml
- hydromt_wflow/data/wflow_sediment/wflow_sediment.toml
- hydromt_wflow/wflow.py
- tests/test_model_methods.py
Fixes number of smaller I/O issues
Fixes #276 
Bit and pieces of code.
No.
> Small I/O fixes

- .github/workflows/test_conda_forge.yml
- pyproject.toml
- tests/conftest.py
- tests/test_model_class.py
Fixes #287
I investigated why the error did not show up in our tests. There is two reasons for it:
- installing hydromt_wflow from conda-forge results in different packages being installed than installing from an environment file even if all the dependencies listed are the same and version controls are the same. For example, installing from conda-forge gives hydromt 0.9.4 and xarray 2024.9.0 while installing from the environment file gives hydromt 0.10.0 and xarray 2024.3.0
- in our tests, we also build a model with too coarse resolution for this specific error to show. If we use the settings of the piave as in the jupyter notebooks (which is the first thing external user try) rather than the test, then the error showed up. 
So I decided to create a new test workflow where we can check if …
> add a test to build model using direct conda forge install

- docs/changelog.rst
- hydromt_wflow/wflow.py
- hydromt_wflow/workflows/landuse.py
No issue was opened but there was a mistake in the unit for preparing mapping tables of LAI from landuse in setup_laimaps.
Other small IO issues from the previous release:
- write_states argument in write
- creation of staticgeoms dir if dir_input is present: Fixes #296 
> Bugfix lai and other small IO errors

- docs/api.rst
- docs/changelog.rst
- docs/user_guide/wflow_model_setup.rst
- hydromt_wflow/wflow.py
- hydromt_wflow/workflows/soilparams.py
- tests/test_model_methods.py
no issue
Within the FAO projects, we tested the approach of Bonetti to enhance the estimation of saturated hydraulic conductivity based on vegetation characteristics (here LAI). This method is now implemented in hydromt_wflow. The method requires to have run setup_LAI and setup_soilmaps first. A new map KsatVer_vegetation is created in the grid. 
> add method for KsatVer vegetation based on paper Bonetti et al (2021)

- .github/workflows/test_stable.yml
- docs/changelog.rst
- hydromt_wflow/__init__.py
- hydromt_wflow/pcrm.py
- hydromt_wflow/wflow.py
- hydromt_wflow/workflows/demand.py
- pyproject.toml
Fixes #322 
See also: https://github.com/conda-forge/hydromt_wflow-feedstock/pull/21
Fix and small release to fix support for python 3.9. Will be dropped again when moving to hydromt v1 / wflow v1
> in the end, decided to drop support already to avoid additional testing for python 39
> python 39 support

- .github/workflows/test_dev.yml
- hydromt_wflow/workflows/soilparams.py
- make_env.py
- pyproject.toml
Fixes #328 
The issue was likely related to using numpy<2 in combination with recent pyflwdir update.
Requires Hydromt core v0.10.1 patch release
> unpin numpy and xarray

- pyproject.toml
Noticed `pytest-timeout` was specified in the `pyproject.toml` was specified twice, so I removed that. 
> remove duplicate dependency in pyproject.oml

- docs/changelog.rst
- hydromt_wflow/utils.py
- hydromt_wflow/wflow.py
- tests/test_model_class.py
Fixes #325 
Previously the grid was masked to the subcatch but only on write, meaning that if you read and wanted to do comparisons or make statistics you'd either have to do the masking manually, or you got wrong results. This is quite counterintuitive, so we moved the masking from the writing to the setting of the grid. 
Some extra contingencies had to be added since at the time of setting any grid, the subcatch might not exist (yet) or be not relevant, so in those cases we just do nothing. 
The clipping is applied again on the write to preserve previous behaviour. perhaps this is unnecessary, but I did it to be sure. This can easily be removed in necessary. 
I also fixed a new mistakes in the error reporting code I noticed while I was busy, but these are non-functional so it's not a …
> Masking grid with subcatch on set instead of on write

- hydromt_wflow/workflows/forcing.py
Fixes #354 
I added an if-statement to check if wradlib is installed and then create the interpolation_classes dict
> wradlib interpolation_classes dict only created when wradlib is installed

- hydromt_wflow/pcrm.py
- hydromt_wflow/utils.py
- hydromt_wflow/wflow.py
- hydromt_wflow/wflow_sediment.py
- hydromt_wflow/workflows/demand.py
- hydromt_wflow/workflows/landuse.py
- hydromt_wflow/workflows/soilgrids.py
The failing quality gate of sonarqube on main was really bothering me and it seemed to be entirely due to using `Union` instead of the new `|` syntax in python 3.10, so I fixed those. With this, the sonar workflow should also be green again on main. Sadly sonarqube doesn't show which issues it will close, but since there are no issues raised in the touched code, I think it should be fine. The coverage needs to be improved at some point but I don't want this PR to get too big so I'll leave that for now. 
Should probably be merged after release is done
> change Uniont types to | notation

- pixi.lock
- pyproject.toml
Dependabot wanted to update the nbconvert version, which was pinned because of a specific issue. I checked locally and the issue seems to be gone, so I think we can remove the pin completely. 
> release nbconvert pin

- docs/getting_started/installation.rst
Fixes #324
For global installation the user must install and expose `hydromt` instead of `hydromt_wflow`
@savente93 specifying `pixi global install hydromt --with hydromt_wflow` results in hydromt version 1.1.0 with hydromt_wflow version 0.2.1. So I included a warning block that the user needs to specify the hydromt version in order to get the latest hydromt_wflow version. With the idea  that the warning block can be removed when hydromt_wflow is compatible with hydromt v1 (#351 #332). What do you think?
I have restricted the hydromt version now. Or would it make more sense to specify the hydromt_wflow version instead of hydromt?
> fix: change pixi global installation

- docs/changelog.rst
- hydromt_wflow/data/wflow/wflow_sbm.toml
- hydromt_wflow/naming.py
- hydromt_wflow/utils.py
- hydromt_wflow/wflow.py
- hydromt_wflow/wflow_sediment.py
- pixi.lock
- pyproject.toml
- tests/data/grouped_model_config.toml
- tests/test_utils.py
Fixes #232 
It turns out that `tomlkit` is quite a buggy implementation so this ended up taking quite long but we got there in the end. The rule we ended up with in the end is that when a value is set, it will be added to the most specific existing table in the config, if this does not exist it will be added to the root. This does mean that if for example the config file should have an input block like so:
```toml
[input.static]
foo = "bar"
mew = "bark"
```
then the table should be added to the toml document before hand even if there are no keys for it yet like so:
```toml
[input.static]
```
Then subsequent sets will be added to this table 
> Preserve existing structure of toml config files on write

- .gitignore
- examples/convert_staticmaps_to_mapstack.ipynb
Late review of updated notebook in PR #408 
Sorry if it was not clear in the issue but the part that fully updates the staticmaps based on all tif files is not something that works. It because some of the variable have a third dimension (layer or time) and when you merge, instead of getting a unique variable (eg c) you then get (c_1, c_2, c_3 etc) so Wflow does not run.
Else all good! I mainly added a final write at the end of the examples to avoid people saying that the changes do not work after running the notebook :) (it happened before for the 1D connection example notebook)
> update staticmaps_to_mapstack example

- docs/changelog.rst
- hydromt_wflow/utils.py
Fixes error on absence of output header
Simply add the dictionary for 'output' when none is present. This is done under the if statements of netcdf (scalar) and csv. No test has been written because it would require a separate file, which seems overkill. The reason for the necessity of a separate file stems from the fact that the model is read/ re-read in `upgrade_to_v1_wflow`, which means that any pop operation on the config file is nullified.
> Small conversion fix

- .github/workflows/publish.yml
- MANIFEST.in
- hydromt_wflow/__init__.py
- hydromt_wflow/version.py
- pixi.lock
- pyproject.toml
Fixes nothing in particular, but setuptools seems a bit more flexible albeit more verbose.
Setuptools as backend with the necessary adjustments to make it work. Moved versioning to a separate file. Added MANIFEST to control the additions to the source distribution. 
No.
> Setuptools backend

- pixi.lock
- tests/test_model_class.py
- tests/test_model_methods.py
#347 
Unskip related tests after PR buffer for get_rasterdataset was merged in core
> re-enable get_rasterdataset buffer tests

- examples/data/wflow_upgrade/sbm/wflow_sbm_v0x.toml
- hydromt_wflow/version_upgrade.py
- tests/data/wflow_v0x/sbm/wflow_sbm_v1.toml
Fixes #493
v0 to v1 upgrade now also checks for csv.column.map and updates it in the new output variable output.csv.column.map.
"lateral.river.lake.locs" and "lateral.river.reservoir.locs" become "reservoir_location__count"
> Update output.csv.map if pointing to lake.locs

- hydromt_wflow/version_upgrade.py
Fixes #564 
Added support to convert riverlength_bc. Setting was moved from model options to `input.static`. Also, support for a layer of the staticmaps was added, which means that a `.value` needs te be added in case it is a value right now.
I had to move the cross_options sections to after the creation of the input fields, as these lines created new (empty) dictionaries.
> Convert riverlength_bc setting
