Deltares/hydromt_wflow

- .github/workflows/docs.yml
- README.rst
- docs/conf.py
- environment.yml
- examples/README.rst
- pyproject.toml
* build pages with github actions
* setup binder
> setup pages and binder

- .gitignore
- docs/conf.py
- docs/examples/index.rst
- examples/README.rst
- examples/base_plots.ipynb
- examples/build_model.ipynb
- examples/nc_to_gtiff.ipynb
- examples/wflow_build.ini
- examples/wflow_extend_sediment.ini
- examples/wflow_sediment_build.ini
- hydromt_wflow/wflow.py
- hydromt_wflow/wflow_sediment.py
- hydromt_wflow/workflows/river.py
- tests/data/wflow_piave_build_subbasin.ini
- tests/data/wflow_sediment_piave_build_subbasin.ini
* change all `source_name` arguments to `<>_fn`
* change all hydro_merit to merit_hydro
* remove redundant wflow root subfolders
> update setup function argument names

- docs/changelog.rst
- docs/user_guide/sediment/components.rst
- docs/user_guide/wflow/components.rst
- hydromt_wflow/wflow.py
Create a component to prepare wflow maps in staticmaps used to save wflow output for specific areas (eg. rainfall over city area, water balance per district, recharge over an aquifer...).
The new component for this is setup_areamap(area_fn, col2raster).
> Add setup_areamap component for wflow output area from vector file

- docs/changelog.rst
- examples/wflow_piave_clip/wflow_sbm.toml
- examples/wflow_piave_subbasin/wflow_sbm.toml
- hydromt_wflow/data/wflow/wflow_sbm.toml
default add lines for glacier parameters and extent
> add lines glacier toml

- hydromt_wflow/wflow.py
- tests/test_model_class.py
Add extra tests for on staticmaps dtype as well as values.
Bugfix for wflow_gauges dtype #50
> Tests on staticmaps dtypes

- hydromt_wflow/workflows/river.py
Just confirmed with @DirkEilander that this is a good fix. So I think we can merge to main.
> fix small bug?

- docs/changelog.rst
- envs/hydromt-wflow.yml
- envs/test_env.yml
- hydromt_wflow/wflow.py
> read boolean pcr maps as int type

- docs/changelog.rst
- hydromt_wflow/wflow.py
as discussed with @hboisgon, this fixes the problem of crs
> fix error crs derive subcatch

- docs/changelog.rst
- hydromt_wflow/wflow.py
I had an issue deriving a parameter which had values of 0 within the domain when running wflow. I would suggest to put no data to -999 instead of 0 in the function
> no data value in setup_areamap to -999

- docs/changelog.rst
- examples/wflow_piave_clip/wflow_sbm.toml
- examples/wflow_piave_subbasin/wflow_sbm.toml
- hydromt_wflow/wflow.py
> Update times in setup_*forcing methods

- docs/changelog.rst
- hydromt_wflow/wflow.py
> fix wrong default value setup_laimaps

- docs/getting_started/installation.rst
- environment.yml
- examples/README.rst
- remove hydromt-wflow dependencies from environment.yml
- make installing using this file the recommended way
- update readme for examples
> update install guide

- .github/workflows/docs.yml
- .github/workflows/tests.yml
- docs/user_guide/wflow_build.rst
- environment.yml
- envs/hydromt-wflow-min.yml
- envs/hydromt-wflow.yml
- envs/test_env.yml
- examples/build_model.ipynb
- examples/build_sediment.ipynb
- examples/update_model_landuse.ipynb
- examples/wflow_build.ini
- examples/wflow_sediment_build.ini
- hydromt_wflow/workflows/basemaps.py
- hydromt_wflow/workflows/landuse.py
- hydromt_wflow/workflows/ptf.py
- hydromt_wflow/workflows/soilgrids.py
- pyproject.toml
- tests/data/wflow_piave_build_subbasin.ini
- tests/data/wflow_sediment_piave_build_subbasin.ini
- tests/test_model_class.py
I updated all the HydroMT CLI calls that use region and resolution arguments in the examples. As well as adding res arguments to wflow_build.ini and wflow_sediment_build.ini
> Updated hydromt CLI calls using region and res arguments

- docs/changelog.rst
- docs/dev_guide/dev_install.rst
changes in docs of developer install linked to issue #167
also updated the changelog after the toml_template PR (forgot to do in that review).
> update doc dev install and changelog

- hydromt_wflow/wflow.py
Checks whether keys are present in config object, before trying to remove them, as this was causing errors. Fixes #185
> bugfix config updating

- docs/changelog.rst
- hydromt_wflow/wflow.py
- hydromt_wflow/workflows/basemaps.py
- pyproject.toml
- tests/conftest.py
- tests/test_model_class.py
- tests/test_model_methods.py
> fix update clip_geom/mask in core

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/documentation_improvement.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
> Lower case for labels in issue templates

- docs/changelog.rst
- hydromt_wflow/__init__.py
- pyproject.toml
> bump versions; prep changelog

- docs/user_guide/sediment_build.rst
- docs/user_guide/wflow_build.rst
> small doc update

- docs/changelog.rst
- hydromt_wflow/__init__.py
- hydromt_wflow/wflow.py
- pyproject.toml
Fixes #237 
Release preparation
No.
> Release v0.5.0

- docs/changelog.rst
- hydromt_wflow/__init__.py
> post release commit

- docs/api.rst
- docs/changelog.rst
- docs/user_guide/wflow_model_setup.rst
- hydromt_wflow/wflow.py
- hydromt_wflow/workflows/__init__.py
- hydromt_wflow/workflows/soilparams.py
- tests/test_model_methods.py
Fixes #228 
Raw implementation of the setup from #249 
No.
> Setup KsatHorFrac

- docs/api.rst
- docs/changelog.rst
- docs/user_guide/wflow_model_setup.rst
- hydromt_wflow/wflow.py
- hydromt_wflow/workflows/__init__.py
- hydromt_wflow/workflows/forcing.py
- tests/conftest.py
- tests/test_model_methods.py
Fixes #69
For now just simple reprojection of PET without any complex correction when downscaling. This can be investigated in the future.
> add setup_pet_forcing method

- docs/changelog.rst
- hydromt_wflow/wflow.py
> Able to set outgoing grid name

- docs/changelog.rst
- hydromt_wflow/__init__.py
> Post v0.6.0 release

- docs/changelog.rst
> Small docs fix

- docs/changelog.rst
- hydromt_wflow/wflow.py
No issue was open
Unable to run Wflow with NaN temp cells in model domain, and hence added the option to interpolate temperatures values to these cells. 
> added temp fillna method

- docs/changelog.rst
- docs/getting_started/faq.rst
- examples/convert_staticmaps_to_mapstack.ipynb
- hydromt_wflow/__init__.py
- hydromt_wflow/pcrm.py
- hydromt_wflow/wflow.py
- hydromt_wflow/workflows/forcing.py
Fixes #284
Fixes #288 
Fixes #270 
See related issues for descriptions.
> Fixes of small issues

- docs/changelog.rst
- hydromt_wflow/__init__.py
Prepare the 0.6.1 with some bugfixes and xarray pin for conda forge install.
> prepare release 0.6.1

- docs/changelog.rst
- hydromt_wflow/__init__.py
Update changelog and version after release.
> post release update

- docs/changelog.rst
- hydromt_wflow/__init__.py
Prepare changelog and version post-release of v0.7.0
> Post release 0.7.0

- examples/prepare_ldd.ipynb
Using this example caused an error, adding this rename solved it
> Add rename to example prepare_ldd notebook

- .github/workflows/test_dev.yml
- pyproject.toml
This was accidentally merged because I was a little trigger happy with merging. This reverts the bit that shouldn't have made it into main.
> release hydromt git dependency

- .github/dependabot.yml
- .github/workflows/pre_commit_auto_update.yml
Copy the dependabot config from core, as well as `pre_commit_auto_update.yml`
> add dependabot.yml

- docs/changelog.rst
- hydromt_wflow/__init__.py
> Post release

- docs/changelog.rst
- docs/dev_guide/dev_install.rst
- docs/getting_started/installation.rst
- pixi.lock
- pyproject.toml
Fixes #324 
I think it's better to have instructions stand on it's own so I copied some stuff from core. Other than that I just added the warning about the commercial stuff in anaconda, and expanded the explanations of pixi. Since pixi is also the preferred way to setup development envs because of the tasks etc. I also expanded on that in the dev install guide. This also aligns us better with the install guide of core. 
> Improve installation docs 

- docs/getting_started/installation.rst
Fixes #324
I saw a formatting typo in the docs so fixed it, and added extra info to additional packages
> Additional improvements to installation docs

- pixi.lock
- pyproject.toml
Add solve-groups to simplify pixi solving.
Making sure that python is installed in full, slim, and docs.
And add solve-groups to ensure that the different environments have the same versions.
> Add python to slim, full, and docs.

- hydromt_wflow/__init__.py
- hydromt_wflow/components/__init__.py
- hydromt_wflow/components/config.py
- hydromt_wflow/components/grid.py
- hydromt_wflow/components/staticmaps.py
- hydromt_wflow/utils.py
- hydromt_wflow/version.py
- hydromt_wflow/wflow.py
- hydromt_wflow/wflow_sediment.py
- pixi.lock
- tests/components/conftest.py
- tests/components/test_config_component.py
Fixes #342
Created a custom wflow config component based on the base ModelComponent class. 
This class uses `tomlkit.TOMLDocument` as it's internal data structure.
`set_config` and `get_config` methods were taken from the general utils submodule.
No.
> Config component

- .gitignore
- .vscode/launch.json
- .vscode/settings.json
Add pytest settings
Add SonarQube Cloud settings
Add formatting settings
Remove .vscode from .gitignore
> Share launch configuration and settings for vs code

- hydromt_wflow/utils.py
Fixes #491 
Compared to v0.8.0, v1.0.0-rc1 has in `WflowModel.set_grid()` these extra lines:
```python
...
if isinstance(data, np.ndarray):
if name is not None:
self.logger.warning(f"Layer {name} will not be masked with basins.")
elif self._MAPS["basins"] in self.grid:
data = utils.mask_raster_from_layer(
data, self.grid[self._MAPS["basins"]]
)  # <-- this is where the error occurs
elif self._MAPS["basins"] in data:
data = utils.mask_raster_from_layer(data, data[self._MAPS["basins"]])
...
```
So I added a check + reprojection to the `mask_raster_from_layer` util function. 
The only place this function is used is in `set_grid()`.
The script I used to reproduce the bug: (works in v0.8.0 and errors in v1.0.0-rc1)
```python 
from pathlib import Path
from hydromt_wflow import WflowModel
def …
```
> fix: conditional reprojection if shapes of the mask & data do not align

- hydromt_wflow/workflows/basemaps.py
- tests/test_model_methods.py
> Re enable model methods tests

- hydromt_wflow/components/__init__.py
- hydromt_wflow/components/tables.py
- hydromt_wflow/wflow.py
- hydromt_wflow/workflows/demand.py
- tests/test_model_methods.py
Fixes #344 
Use directly the component from core without any changes needed
> feat: implement tables component

- examples/wflow_update_v1_sediment.yml
Otherwise it uses the wrong staticmaps file in the config while writing.
Fixes #496 
> Move write_config to the end of the yaml config

- hydromt_wflow/data/fetch.py
- hydromt_wflow/version_upgrade.py
- hydromt_wflow/wflow.py
- hydromt_wflow/wflow_sediment.py
- hydromt_wflow/workflows/basemaps.py
- hydromt_wflow/workflows/connect.py
- hydromt_wflow/workflows/demand.py
- hydromt_wflow/workflows/forcing.py
- hydromt_wflow/workflows/gauges.py
- hydromt_wflow/workflows/glaciers.py
- hydromt_wflow/workflows/landuse.py
- hydromt_wflow/workflows/reservoirs.py
- hydromt_wflow/workflows/river.py
- hydromt_wflow/workflows/rootzoneclim.py
- hydromt_wflow/workflows/soilgrids.py
Instead, just call logging.getLogger with "hydromt." as prefix.
Tested with build_model.ipynb and gives the exact same results.
Fixes #527 
I have not added new tests, because I don't think anything changed. I just get the logger in a different fashion.
Proof:
> Removed all argument passing of logger

- README.rst
- docs/api.rst
- docs/conf.py
- docs/dev_guide/roadmap.rst
- docs/dev_guide/software_design.rst
- docs/getting_started/faq.rst
- docs/user_guide/process_analyze.rst
- docs/user_guide/sediment_build.rst
- docs/user_guide/sediment_clip.rst
- docs/user_guide/sediment_model_setup.rst
- docs/user_guide/sediment_update.rst
- docs/user_guide/wflow_build.rst
- docs/user_guide/wflow_clip.rst
- docs/user_guide/wflow_model_setup.rst
- docs/user_guide/wflow_update.rst
- examples/build_model.ipynb
- examples/build_sediment.ipynb
- examples/clip_model.ipynb
- examples/convert_staticmaps_to_mapstack.ipynb
- examples/plot_wflow_results.ipynb
- examples/prepare_ldd.ipynb
- examples/update_model_gauges.ipynb
- examples/update_model_landuse.ipynb
- hydromt_wflow/wflow.py
- hydromt_wflow/wflow_sediment.py
- hydromt_wflow/workflows/soilgrids.py
- pixi.lock
- pyproject.toml
Fixes #500 
I added a sphinx extension to automatically check links. While I was in there I also fixed a number of rst syntax errors.
> Fix links in docs, and add link checker to sphinx

- pixi.lock
- tests/conftest.py
> fixed issue with new xarray changes

- examples/wflow_update_v1_sbm.yml
Although the current example model doesn't have any lake files, it's good to show in the documentation that lakes are being migrated.
Fixes #574 
> Add line on writing tables
